### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by jfmdev** [AdvancedThreatAnalytics/threat-analytics-search#57]
The release of v5.0 required a fair amount of testing to verify that current features weren't broken and that settings were being migrated correctly:

1. Installation
   * 1.1) Upgrading
      - [x] 1.1.1) Settings from previous version (v4.0) of the extension should be migrated when upgrading (to 5.0).
      - [x] 1.1.2) Settings should be set to default values if previous extension had corrupted data.
      - [x] 1.1.3) Settings shouldn't be refreshed when upgrading and previous version was v5.0
   * 1.2) First install
      - [x] 1.2.1) Settings should be populated with data from settings.json if file on Configuration URL is unreachable.
      - [x] 1.2.2) Settings should be override with values read from the file defined by the Configuration URL.
2. Basic Settings
   * 2.1) Configuration File Options
      - [x] 2.1.1) Clicking "Enable groups" should automatically add/remove groups from the contextual menu.
      - [x] 2.1.2) If groups aren't enabled, groups names shouldn't be updated when refreshing.
      - [x] 2.1.3) Settings should be refreshed with external files.
      - [x] 2.1.4) Settings should be refreshed with external encripted files.
      - [x] 2.1.5) Settings should be refreshed automatically, if enabled.
      - [x] 2.1.6) Settings shouldn't be refreshed automatically, if disabled.
   * 2.2) Search Result Options
      - [x] 2.2.1) Check behavior of "Open results in a background tab" setting.
      - [x] 2.2.2) Check behavior of "The new tab should be next to the current tab" setting.
      - [x] 2.2.3) Check behavior of "Open group tabs in new window" setting.
      - [x] 2.2.4) Check behavior of "Show link to extension options at the end of context menu" setting.
   * 2.3) Import/Export
      - [x] 2.3.1) Changing the settings should modify the JSON textarea.
      - [x] 2.3.2) JSON files should be imported correctly.
3. Search Providers
   * [x] 3.1) Changing the order on the Options page should change the order on the contextual menu.
   * [x] 3.2) Disabling/enabling a search provider on the Options page should add/remove his item from the contextual menu.
   * [x] 3.3) Modifying the name and URL of a search provider should update his corresponding item on the contextual menu.
   * [x] 3.4) If you add a new search provider, it should be appended to the contextual menu.
   * [x] 3.5) If you remove a search provider, it should be removed from the contextual menu.
   * [x] 3.6) Verify that POST search providers works as on version 4.0.
   * [x] 3.7) Verify that Proxy search providers works as on version 4.0.
4. Groups
   * [x] 4.1) Clicking on a group should tabs for all search providers on that group (please test this for all three groups).
   * [x] 4.2) If you add and remove search providers from a group, and then you click it again, the new group should be opened.
   * [x] 4.3) If you rename or enable/disable groups, the change should be automatically reflected on the context menu.
5. Special Search Providers
   * 5.1) Verify default queries
      - [x] 5.1.1) Verify that menu items for CBC opens the same URLs (with the same query parameters) on both v4.0 and 5.0
      - [x] 5.1.2) Verify that menu items for NWI opens the same URLs (with the same query parameters) on both v4.0 and 5.0
      - [x] 5.1.3) Verify that menu items for RSA opens the same URLs (with the same query parameters) on both v4.0 and 5.0
   * 5.2) Verify adding/removing queries
      - [x] 5.2.1) Verify that adding/removing queries from CBC updates the contextual menu accordingly, and that new queries are invoked with the parameters you set.
      - [x] 5.2.2) Verify that adding/removing queries from NWI updates the contextual menu accordingly, and that new queries are invoked with the parameters you set.
      - [x] 5.2.3) Verify that adding/removing queries from RSA updates the contextual menu accordingly, and that new queries are invoked with the parameters you set.
   * 5.3) Verify edit configuration
      - [x] 5.3.1) Verify that editing the configuration from CBC changes the URLs which are opened by the corresponding menu items. Also verify that "Enable Carbon Black Settings" add/removes the items from the contextual menu and that "Switch Focus to New Tab" changes if (after clicking a menu item) the opened tab is focused or not.
      - [x] 5.3.2) Verify that editing the configuration from NWI changes the URLs which are opened by the corresponding menu items. Also verify that "Enable NetWitness Investigator Settings" add/removes the items from the contextual menu.
      - [x] 5.3.3) Verify that editing the configuration from RSA changes the URLs which are opened by the corresponding menu items. Also verify that "Enable RSA Security Analytics Settings" add/removes the items from the contextual menu and that "Switch Focus to New Tab" changes if (after clicking a menu item) the opened tab is focused or not.
      - [x] 5.3.4) Verify that the "Paste example link from Security Analytics Investigation to autofill settings" and "Paste example link from NetWitness Investigator to autofill settings" inputs works a before (this inputs should populate some of the others inputs once you paste some particular URL on them, you could ask Mackey for some examples for this).

> Source: https://github.com/AdvancedThreatAnalytics/threat-analytics-search-deprecated/pull/13#issuecomment-829593090

Most of this items will need to be re-tested when releasing newer versions, hence we should automatize them, to make the deployment process more effortless.
